{{- if and .Values.alertmanager.enabled
           .Values.alertmanager.persistentVolume.enabled
           (not .Values.alertmanager.statefulSet.enabled)
           .Values.alertmanager.persistentVolume.existingClaim -}}
{{- with .Values.alertmanager.persistentVolume }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "prometheus.alertmanager.labels" $ | nindent 4 }}
  name: {{ template "prometheus.alertmanager.fullname" $ }}
  {{- include "prometheus.namespace" $ | nindent 2 }}
spec:
  accessModes:
    {{- toYaml .accessModes | nindent 4 }}
  {{- if .storageClass }}
  {{- if (eq "-" .storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .storageClass }}"
  {{- end }}
  {{- end }}
  {{- with .volumeBindingMode }}
  volumeBindingMode: "{{ . }}"
  {{- end }}
  resources:
    requests:
      storage: "{{ .size }}"
  {{- with .selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .volumeName }}
  volumeName: "{{ . }}"
  {{- end -}}
{{- end }}
{{- end -}}
