{{- if .Values.alertmanager.enabled -}}
{{- with .Values.alertmanager.service }}
apiVersion: v1
kind: Service
metadata:
  {{- with .annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "prometheus.alertmanager.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ template "prometheus.alertmanager.fullname" $ }}
  {{- include "prometheus.namespace" $ | nindent 2 }}
spec:
  {{- with .clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range $cidr := . }}
    - {{ $cidr }}
    {{- end }}
  {{- end }}
  ports:
    - name: http
      port: {{ .servicePort }}
      protocol: TCP
      targetPort: 9093
      {{- with .nodePort }}
      nodePort: {{ . }}
      {{- end }}
    {{- if .enableMeshPeer }}
    - name: meshpeer
      port: 6783
      protocol: TCP
      targetPort: 6783
    {{- end }}
  selector:
    {{- include "prometheus.alertmanager.matchLabels" $ | nindent 4 }}
  {{- with .sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  type: "{{ .type }}"
{{- end }}
{{- end }}
