{{- if and .Values.alertmanager.enabled .Values.serviceAccounts.alertmanager.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "prometheus.alertmanager.labels" $ | nindent 4 }}
  name: {{ template "prometheus.serviceAccountName.alertmanager" $ }}
  {{- include "prometheus.namespace" $ | nindent 2 }}
  {{- with .Values.serviceAccounts.alertmanager.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
