{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "prometheus-snmp-exporter.fullname" .  }}
  {{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  {{- end }}
  labels:
    {{- include "prometheus-snmp-exporter.labels" . | indent 4 }}
    {{- range $key, $value := .Values.serviceMonitor.selector }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  endpoints:
  {{- if not (empty .Values.serviceMonitor.endPoints)}}
  {{ range  .Values.serviceMonitor.endPoints}}
  - port: http
    {{- if .interval }}
    interval: {{ .interval }}
    {{- end }}
    honorLabels: {{ .honorLabels }}
    path: {{ .path }}
    {{- if .scrapeTimeout }}
    scrapeTimeout: {{ .scrapeTimeout }}
    {{- end }}
    params:
      module:
      - {{ .module }}
      target:
      - {{ .target }}
    {{- if .metricRelabelings }}
    metricRelabelings: {{ toYaml .metricRelabelings | nindent 8 }}
    {{- end }}
    {{- if .relabelings }}
    relabelings: {{ toYaml .relabelings | nindent 8 }}
    {{- end }}
  {{- end }}
  {{- else }}
  - port: http
    honorLabels: true
    path: /snmp
  {{- end }}
  selector:
    matchLabels:
      {{- include "prometheus-snmp-exporter.selectorLabels" . | indent 6 }}
{{- end -}}
