{{- if .Values.rbac.create }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ template "prometheus-cloudwatch-exporter.fullname" . }}
  labels:
    {{- include "prometheus-cloudwatch-exporter.labels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets","configmap"]
    resourceNames: ["{{ template "prometheus-cloudwatch-exporter.fullname" . }}"]
    verbs: ["get"]
{{- end }}