apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "prometheus-cloudwatch-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-cloudwatch-exporter.labels" . | indent 4 }}
data:
  config.yml: |
    {{ tpl .Values.config . | nindent 4 }}
