{{- if and (not .Values.aws.role) (not .Values.aws.secret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prometheus-cloudwatch-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-cloudwatch-exporter.labels" . | indent 4 }}
type: Opaque
data:
  {{ if .Values.aws.aws_access_key_id }}
  aws_access_key_id: {{ .Values.aws.aws_access_key_id | b64enc | quote }}
  {{ end }}
  {{ if .Values.aws.aws_secret_access_key }}
  aws_secret_access_key: {{ .Values.aws.aws_secret_access_key | b64enc | quote }}
  {{ end }}
{{- end }}
