apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-cloudwatch-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  labels:
    {{- include "prometheus-cloudwatch-exporter.labels" . | indent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: container-port
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{- include "prometheus-cloudwatch-exporter.selectorLabels" . | indent 4 }}
