{{- if and .Values.rbac.create .Values.rbac.useClusterRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
  name: {{ include "kube-state-metrics.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  {{- if .Values.rbac.useExistingRole }}
  name: {{ .Values.rbac.useExistingRole }}
  {{- else }}
  name: {{ include "kube-state-metrics.fullname" . }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-state-metrics.serviceAccountName" . }}
    namespace: {{ include "kube-state-metrics.namespace" . }}
{{- end }}
