{{- if .Values.podDisruptionBudget }}
apiVersion: {{ include "kube-state-metrics.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "kube-state-metrics.fullname" . }}
  namespace: {{ include "kube-state-metrics.namespace" . }}
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kube-state-metrics.name" . }}
  {{- toYaml .Values.podDisruptionBudget | nindent 2 }}
{{- end }}
