{{- if and (.Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy") .Values.podSecurityPolicy.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
  name: psp-{{ include "kube-state-metrics.fullname" . }}
rules:
  {{- $kubeTargetVersion := default .Capabilities.KubeVersion.GitVersion .Values.kubeTargetVersionOverride }}
  {{- if semverCompare "> 1.15.0-0" $kubeTargetVersion }}
  - apiGroups: ['policy']
  {{- else }}
  - apiGroups: ['extensions']
  {{- end }}
    resources: ['podsecuritypolicies']
    verbs:     ['use']
    resourceNames:
      - {{ include "kube-state-metrics.fullname" . }}
{{- end }}
