{{- if and .Values.rbac.create (not .Values.rbac.useClusterRole) }}
{{- range (join "," $.Values.namespaces) | split "," }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "kube-state-metrics.labels" $ | nindent 4 }}
  name: {{ include "kube-state-metrics.fullname" $ }}
  namespace: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  {{- if $.Values.rbac.useExistingRole }}
  name: {{ $.Values.rbac.useExistingRole }}
  {{- else }}
  name: {{ include "kube-state-metrics.fullname" $ }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-state-metrics.serviceAccountName" $ }}
    namespace: {{ include "kube-state-metrics.namespace" $ }}
{{- end }}
{{- end }}
