apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-state-metrics.fullname" . }}
  namespace: {{ include "kube-state-metrics.namespace" . }}
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.prometheusScrape }}
    prometheus.io/scrape: '{{ . }}'
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: "{{ .Values.service.type }}"
  ports:
    - name: "http"
      protocol: TCP
      port: {{ .Values.service.port | default 8080}}
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
      targetPort: {{ .Values.service.port | default 8080}}
    {{- if .Values.selfMonitor.enabled }}
    - name: "metrics"
      protocol: TCP
      port: {{ .Values.selfMonitor.telemetryPort | default 8081 }}
      targetPort: {{ .Values.selfMonitor.telemetryPort | default 8081 }}
      {{- with .Values.selfMonitor.telemetryNodePort }}
      nodePort: {{ . }}
      {{- end }}
    {{- end }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ . }}"
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range $cidr := . }}
    - {{ $cidr }}
    {{- end }}
  {{- end }}
  {{- if .Values.autosharding.enabled }}
  clusterIP: None
  {{- else if .Values.service.clusterIP }}
  clusterIP: "{{ .Values.service.clusterIP }}"
  {{- end }}
  selector:
    {{- include "kube-state-metrics.selectorLabels" . | nindent 4 }}
