{{- if and (.Capabilities.APIVersions.Has "autoscaling.k8s.io/v1") .Values.verticalPodAutoscaler.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "kube-state-metrics.fullname" . }}
  namespace: {{ include "kube-state-metrics.namespace" . }}
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: {{ include "kube-state-metrics.name" . }}
        {{- with .Values.verticalPodAutoscaler.controlledResources }}
        controlledResources: {{ . }}
        {{- end }}
        {{- with .Values.verticalPodAutoscaler.maxAllowed }}
        maxAllowed:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.verticalPodAutoscaler.minAllowed }}
        minAllowed:
          {{- toYaml . | nindent 10 }}
        {{- end }}
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  {{ include "kube-state-metrics.fullname" . }}
  {{- if .Values.verticalPodAutoscaler.updatePolicy }}
  updatePolicy:
    {{- with .Values.verticalPodAutoscaler.updatePolicy.updateMode }}
    updateMode: {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
