{{- if and .Values.pushgateway.persistentVolume.enabled (not .Values.pushgateway.persistentVolume.existingClaim) -}}
{{- with .Values.pushgateway.persistentVolume }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "prometheus.pushgateway.labels" $ | nindent 4 }}
  name: {{ template "prometheus.pushgateway.fullname" $ }}
  {{- include "prometheus.namespace" $ | nindent 2 }}
spec:
  accessModes:
    {{- toYaml .accessModes | nindent 4 }}
  {{- if .storageClass }}
  {{- if (eq "-" .storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .storageClass }}"
  {{- end }}
  {{- end }}
  {{- with .volumeBindingMode }}
  volumeBindingMode: "{{ . }}"
  {{- end }}
  resources:
    requests:
      storage: "{{ .size }}"
  {{- with .volumeName }}
  volumeName: "{{ . }}"
  {{- end }}
{{- end }}
{{- end -}}
