{{- if .Values.pushgateway.enabled -}}
{{- with .Values.pushgateway.service }}
apiVersion: v1
kind: Service
metadata:
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "prometheus.pushgateway.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ template "prometheus.pushgateway.fullname" $ }}
  {{- include "prometheus.namespace" $ | nindent 2 }}
spec:
  {{- with .clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range $cidr := . }}
    - {{ $cidr }}
    {{- end }}
  {{- end }}
  ports:
    - name: http
      port: {{ .servicePort }}
      protocol: TCP
      targetPort: 9091
      {{- with .nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "prometheus.pushgateway.matchLabels" $ | nindent 4 }}
  type: "{{ .type }}"
{{- end }}
{{- end }}
