{{- if and .Values.pushgateway.enabled .Values.pushgateway.verticalAutoscaler.enabled -}}
{{- with .Values.pushgateway.verticalAutoscaler }}
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  labels:
    {{- include "prometheus.pushgateway.labels" $ | nindent 4 }}
  name: {{ template "prometheus.pushgateway.fullname" $ }}-vpa
  {{- include "prometheus.namespace" $ | nindent 2 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ template "prometheus.pushgateway.fullname" $ }}
  updatePolicy:
    updateMode: {{ .updateMode | default "Off" | quote }}
  {{- with .containerPolicies }}
  resourcePolicy:
    containerPolicies: {{ . | default list | toYaml | trim | nindent 4 }}
  {{- end }}
{{- end -}}
{{- end -}}
