{{- if and .Values.kubeApiServer.enabled .Values.kubernetesServiceMonitors.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-apiserver
  {{- if .Values.prometheus.prometheusSpec.ignoreNamespaceSelectors }}
  namespace: default
  {{- else }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  {{- end }}
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-apiserver
  {{- with .Values.kubeApiServer.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  {{- include "servicemonitor.scrapeLimits" .Values.kubeApiServer.serviceMonitor | nindent 2 }}
  endpoints:
  {{- include "kube-prometheus-stack.kubeApiServer.endpoint" (list $ "") }}
  {{- if .Values.kubeApiServer.serviceMonitor.slis }}
  {{- include "kube-prometheus-stack.kubeApiServer.endpoint" (list $ "slis") }}
    path: /metrics/slis
  {{- end }}
  jobLabel: {{ .Values.kubeApiServer.serviceMonitor.jobLabel }}
  namespaceSelector:
    matchNames:
    - default
  selector:
{{ toYaml .Values.kubeApiServer.serviceMonitor.selector | indent 4 }}
{{- end}}
