apiVersion: v2
name: prometheus-operator-crds
description: prometheus-operator-crds collects CRDs from the Prometheus Operator with the ability to interact with them for seamlessly integration with GitOps tools
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
type: application

version: 0.1.0
appVersion: 0.60.1
kubeVersion: ">=1.16.0-0"
