apiVersion: v1
appVersion: "v1.2.0"
description: A Helm chart to export the metrics from Kafka in Prometheus format.
name: prometheus-kafka-exporter
home: https://gkarthiks.github.io/helm-charts/charts/prometheus-kafka-exporter
version: 0.1.2
sources:
  - https://github.com/danielqsj/kafka_exporter
keywords:
  - prometheus
  - kafka
maintainers:
  - name: gkarthiks
    email: github.gkarthiks@gmail.com
engine: gotpl
