apiVersion: v1
appVersion: "v1.2.0"
description: A Helm chart to export the metrics from Kafka in Prometheus format.
name: prometheus-kafka-exporter
home: https://github.com/danielqsj/kafka_exporter
version: 0.1.4
sources:
  - https://gkarthiks.github.io/helm-charts/charts/prometheus-kafka-exporter
keywords:
  - prometheus
  - kafka
maintainers:
  - name: gkarthiks
    email: github.gkarthiks@gmail.com
  - name: golgoth31
    email: golgoth31@notrenet.com
engine: gotpl
annotations:
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://gkarthiks.github.io/helm-charts/charts/prometheus-kafka-exporter
