{{- if and .Values.alertmanager.enabled .Values.alertmanager.serviceMonitor.selfMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "kube-prometheus.fullname" . }}-alertmanager
  namespace: {{ template "kube-prometheus.namespace" . }}
  labels:
    app: {{ template "kube-prometheus.name" . }}-alertmanager
{{ include "kube-prometheus.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ template "kube-prometheus.name" . }}-alertmanager
      release: {{ $.Release.Name | quote }}
      self-monitor: "true"
  namespaceSelector:
    matchNames:
      - {{ printf "%s" (include "kube-prometheus.namespace" .) | quote }}
  endpoints:
  - port: {{ .Values.alertmanager.alertmanagerSpec.portName }}
    {{- if .Values.alertmanager.serviceMonitor.interval }}
    interval: {{ .Values.alertmanager.serviceMonitor.interval }}
    {{- end }}
    path: "{{ trimSuffix "/" .Values.alertmanager.alertmanagerSpec.routePrefix }}/metrics"
{{- if .Values.alertmanager.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.alertmanager.serviceMonitor.metricRelabelings | indent 6) . }}
{{- end }}
{{- if .Values.alertmanager.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .Values.alertmanager.serviceMonitor.relabelings | indent 6 }}
{{- end }}
{{- end }}
