{{- if and .Values.alertmanager.enabled .Values.alertmanager.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kube-prometheus.alertmanager.serviceAccountName" . }}
  namespace: {{ template "kube-prometheus.namespace" . }}
  labels:
    app: {{ template "kube-prometheus.name" . }}-alertmanager
{{ include "kube-prometheus.labels" . | indent 4 }}
{{- if .Values.alertmanager.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.alertmanager.serviceAccount.annotations | indent 4 }}
{{- end }}
imagePullSecrets:
{{ toYaml .Values.global.imagePullSecrets | indent 2 }}
{{- end }}
