{{- if not .Values.rules.existing -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "k8s-prometheus-adapter.fullname" . }}
  namespace: {{ include "k8s-prometheus-adapter.namespace" . }}
  {{- if .Values.customAnnotations }}
  annotations:
  {{- toYaml .Values.customAnnotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "k8s-prometheus-adapter.labels" . | indent 4 }}
data:
  config.yaml: |
{{- if .Values.rules.custom }}
    rules:
{{ toYaml .Values.rules.custom | indent 4 }}
{{- end -}}
{{- if .Values.rules.external }}
    externalRules:
{{ toYaml .Values.rules.external | indent 4 }}
{{- end -}}
{{- if .Values.rules.resource }}
    resourceRules:
{{ toYaml .Values.rules.resource | indent 6 }}
{{- end -}}
{{- end -}}
