# Default values for prometheus-statsd-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: prom/statsd-exporter
  tag: v0.18.0
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

priorityClassName: ""

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP

# statsd-exporter listener settings
# https://github.com/prometheus/statsd_exporter

# webPort is the address on which to expose the /metrics web endpoint
webPort: 9102
# udpPort is the UDP address on which to receive statsd metrics
udpPort: 9125
# tcpPort is the TCP address on which to receive statsd metrics
tcpPort: 9125

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# statsdMappingConfig contains statsd-exporter metric mappings
# https://github.com/prometheus/statsd_exporter#metric-mapping-and-configuration
statsdMappingConfig: |-
  defaults:
    timer_type: histogram
