{{- if .Values.prometheus.monitor.podMonitor }}
apiVersion: {{ .Values.prometheus.monitor.apiVersion | default "monitoring.googleapis.com/v1" }}
kind: PodMonitoring
metadata:
  name: {{ template "prometheus-statsd-exporter.fullname" . }}-metrics
  namespace: {{ default .Release.Namespace .Values.prometheus.monitor.namespace | quote }}
  labels: {{- include "prometheus-statsd-exporter.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
    {{- range $key, $value := .Values.prometheus.monitor.additionalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "prometheus-statsd-exporter.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.prometheus.monitor.scheme }}
      path: {{ .Values.prometheus.monitor.endpoint }}
      {{- if .Values.prometheus.monitor.interval }}
      interval: {{ .Values.prometheus.monitor.interval }}
      {{- end }}
{{- end }}
