{{- with .Values.nodeExporter }}
{{- if .enabled -}}
apiVersion: {{ template "prometheus.daemonset.apiVersion" $ }}
kind: DaemonSet
metadata:
  {{- with .deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "prometheus.nodeExporter.labels" $ | nindent 4 }}
  name: {{ template "prometheus.nodeExporter.fullname" $ }}
  {{- include "prometheus.namespace" $ | nindent 2 }}
spec:
  selector:
    matchLabels:
      {{- include "prometheus.nodeExporter.matchLabels" $ | nindent 6 }}
  {{- with .updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "prometheus.nodeExporter.labels" $ | nindent 8 }}
        {{- with .podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "prometheus.serviceAccountName.nodeExporter" $ }}
      {{- with .extraInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .priorityClassName }}
      priorityClassName: "{{ . }}"
      {{- end }}
      containers:
        - name: {{ template "prometheus.name" $ }}-{{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: "{{ .image.pullPolicy }}"
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            {{- if .hostRootfs }}
            - --path.rootfs=/host/root
            {{- end }}
            {{- if .hostNetwork }}
            - --web.listen-address=:{{ .service.hostPort }}
            {{- end }}
            {{- range $key, $value := .extraArgs }}
            {{- if $value }}
            - --{{ $key }}={{ $value }}
            {{- else }}
            - --{{ $key }}
            {{- end }}
            {{- end }}
          ports:
            - name: metrics
              {{- if .hostNetwork }}
              containerPort: {{ .service.hostPort }}
              {{- else }}
              containerPort: 9100
              {{- end }}
              hostPort: {{ .service.hostPort }}
          {{- with .resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .container.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly:  true
            - name: sys
              mountPath: /host/sys
              readOnly: true
            {{- if .hostRootfs }}
            - name: root
              mountPath: /host/root
              mountPropagation: HostToContainer
              readOnly: true
            {{- end }}
            {{- range .extraHostPathMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly }}
              {{- with .mountPropagation }}
              mountPropagation: {{ . }}
              {{- end }}
            {{- end }}
            {{- range .extraConfigmapMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly }}
            {{- end }}
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .hostNetwork }}
      hostNetwork: true
      {{- end }}
      {{- if .hostPID }}
      hostPID: true
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        {{- if .hostRootfs }}
        - name: root
          hostPath:
            path: /
        {{- end }}
        {{- range .extraHostPathMounts }}
        - name: {{ .name }}
          hostPath:
            path: {{ .hostPath }}
        {{- end }}
        {{- range .extraConfigmapMounts }}
        - name: {{ .name }}
          configMap:
            name: {{ .configMap }}
        {{- end }}
{{- end -}}
{{- end }}
