{{- if and .Values.nodeExporter.enabled .Values.rbac.create }}
{{- if or (default .Values.nodeExporter.podSecurityPolicy.enabled false) (.Values.podSecurityPolicy.enabled) }}
apiVersion: {{ template "rbac.apiVersion" $ }}
kind: Role
metadata:
  labels:
    {{- include "prometheus.nodeExporter.labels" $ | nindent 4 }}
  name: {{ template "prometheus.nodeExporter.fullname" $ }}
  {{- include "prometheus.namespace" $ | nindent 2 }}
rules:
  {{- if and .Values.podSecurityPolicy.enabled
             (.Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy") }}
  - apiGroups: 
      - extensions
    resources: 
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - {{ template "prometheus.nodeExporter.fullname" $ }}
  {{- else }}
  []
  {{- end}}
{{- end }}
{{- end }}
