appVersion: 1.109.0
version: 0.2.0
description: Prometheus OpenCost Exporter
home: https://github.com/opencost/opencost
name: prometheus-opencost-exporter
sources:
- https://github.com/prometheus-community/opencost_exporter
apiVersion: v2
type: application
keywords:
- opencost
- prometheus
- exporter
- finops
maintainers:
- email: mattray@kubecost.com
  name: mattray
