{{- if .Values.kubeControllerManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kube-prometheus.fullname" . }}-kube-controller-manager
  labels:
    app: {{ template "kube-prometheus.name" . }}-kube-controller-manager
    jobLabel: kube-controller-manager
{{ include "kube-prometheus.labels" . | indent 4 }}
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: {{ .Values.kubeControllerManager.service.port }}
      protocol: TCP
      targetPort: {{ .Values.kubeControllerManager.service.targetPort }}
{{- if .Values.kubeControllerManager.endpoints }}{{- else }}
  selector:
    {{- if .Values.kubeControllerManager.service.selector }}
{{ toYaml .Values.kubeControllerManager.service.selector | indent 4 }}
    {{- else}}
    component: kube-controller-manager
    {{- end}}
{{- end }}
  type: ClusterIP
{{- end }}
