{{- if .Values.server.enabled -}}
{{- if not .Values.server.statefulSet.enabled -}}
{{- if .Values.server.persistentVolume.enabled -}}
{{- if not .Values.server.persistentVolume.existingClaim -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- with .Values.server.persistentVolume.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "prometheus.server.labels" . | nindent 4 }}
  name: {{ template "prometheus.server.fullname" . }}
  {{- include "prometheus.namespace" . | nindent 2 }}
spec:
  accessModes:
    {{ toYaml .Values.server.persistentVolume.accessModes | nindent 4 }}
  {{- if .Values.server.persistentVolume.storageClass }}
  {{- if (eq "-" .Values.server.persistentVolume.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.server.persistentVolume.storageClass }}"
  {{- end }}
  {{- end }}
  {{- with .Values.server.persistentVolume.volumeBindingMode }}
  volumeBindingMode: "{{ . }}"
  {{- end }}
  resources:
    requests:
      storage: "{{ .Values.server.persistentVolume.size }}"
  {{- with .Values.server.persistentVolume.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end -}}
  {{- with .Values.server.persistentVolume.volumeName }}
  volumeName: "{{ . }}"
  {{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
