{{- if and .Values.server.enabled .Values.server.service.enabled -}}
{{- with .Values.server.service }}
apiVersion: v1
kind: Service
metadata:
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "prometheus.server.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ template "prometheus.server.fullname" $ }}
  {{- include "prometheus.namespace" $ | nindent 2 }}
spec:
  {{- with .clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range $cidr := . }}
    - {{ $cidr }}
    {{- end }}
  {{- end }}
  ports:
    - name: http
      port: {{ .servicePort }}
      protocol: TCP
      targetPort: 9090
      {{- with .nodePort }}
      nodePort: {{ . }}
      {{- end }}
    {{- if .gRPC.enabled }}
    - name: grpc
      port: {{ .gRPC.servicePort }}
      protocol: TCP
      targetPort: 10901
      {{- with .gRPC.nodePort }}
      nodePort: {{ . }}
      {{- end }}
    {{- end }}
  selector:
  {{- if and $.Values.server.statefulSet.enabled .statefulsetReplica.enabled }}
    statefulset.kubernetes.io/pod-name: {{ template "prometheus.server.fullname" $ }}-{{ .statefulsetReplica.replica }}
  {{- else -}}
    {{- include "prometheus.server.matchLabels" $ | nindent 4 }}
  {{- with .sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  {{- end }}
  type: "{{ .type }}"
{{- end -}}
{{- end -}}