---
prometheusOperator:
  rbac:
    namespaced: true
  namespaces:
    releaseNamespace: true
  kubeletService:
    enabled: false
  additionalRulesForClusterRole:
    - apiGroups:
        - ""
      resources:
        - events
      verbs:
        - create
        - patch
    - apiGroups:
        - storage.k8s.io
      resources:
        - storageclasses
      verbs:
        - get

prometheus:
  rbac:
    namespaced: true
  additionalRulesForClusterRole:
    - apiGroups:
        - ""
      resources:
        - nodes
      verbs:
        - list
        - watch

kubelet:
  enabled: false

coreDns:
  enabled: false

kubeDns:
  enabled: false

kubeApiServer:
  enabled: false

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeProxy:
  enabled: false

kubeScheduler:
  enabled: false