{{- if and .Values.fortigate.targets (eq .Values.fortigate.useExistingSecrets false) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prometheus-fortigate-exporter.fullname" . }}-secret
  labels:
    chart: {{ template "prometheus-fortigate-exporter.chart" . }}
    app: {{ template "prometheus-fortigate-exporter.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  fortigate-key.yaml: |
    {{- toYaml .Values.fortigate.targets | b64enc | nindent 4  }}
{{- end }}
