apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alertmanager.fullname" . }}
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
data:
  {{ .Values.configFileName }}: |
    {{- toYaml .Values.config | default "{}" | nindent 4 }}
