{{- if and .Values.crds.enabled .Values.global.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-crds
    {{- include "kube-prometheus-stack.labels" . | nindent 4 }}
  name: {{ template "kube-prometheus-stack.fullname" . }}-crds
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kube-prometheus-stack.fullname" . }}-crds
subjects:
  - kind: ServiceAccount
    name: {{ template "kube-prometheus-stack.crds.serviceAccountName" . }}
    namespace: {{ template "kube-prometheus-stack.namespace" . }}
{{- end }}
