{{- if and .Values.crds.enabled .Values.crds.serviceAccount.create}}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    {{- if .Values.crds.serviceAccount.annotations }}
    {{ toYaml .Values.crds.serviceAccount.annotations | nindent 4 }}
    {{- end }}
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-crds
    app.kubernetes.io/name: {{ template "kube-prometheus-stack.name" . }}-crds
    app.kubernetes.io/component: crds
    {{ include "kube-prometheus-stack.labels" . | nindent 4 }}
  name: {{ template "kube-prometheus-stack.crds.serviceAccountName" . }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  {{- if .Values.global.imagePullSecrets }}
  imagePullSecrets:
    {{ include "kube-prometheus-stack.imagePullSecrets" . | trim | nindent 4 }}
  {{- end }}
{{- end }}



