{{- if and .Values.prometheus.enabled .Values.global.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.prometheus.rbac.namespaced | ternary "Role" "ClusterRole" }}
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-prometheus
  {{- if .Values.prometheus.rbac.namespaced }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  {{- end }}
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-prometheus
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
rules:
# This permission are not in the kube-prometheus repo
# they're grabbed from https://github.com/prometheus/prometheus/blob/master/documentation/examples/rbac-setup.yml
- apiGroups: [""]
  resources:
  {{- if not .Values.prometheus.rbac.namespaced }}
  - nodes
  - nodes/metrics
  {{- end }}
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
{{- if not .Values.prometheus.rbac.namespaced }}
- nonResourceURLs: ["/metrics", "/metrics/cadvisor"]
  verbs: ["get"]
{{- end }}
{{/* fix(#3338): add required rules to use node-exporter with the RBAC proxy */}}
{{- if and .Values.nodeExporter.enabled (index .Values "prometheus-node-exporter").kubeRBACProxy.enabled }}
- apiGroups: [ "" ]
  resources:
  - services/{{ include "prometheus-node-exporter.fullname" (index .Subcharts "prometheus-node-exporter") }}
  verbs: [ "get", "list", "watch" ]
{{- end }}
{{- if .Values.prometheusOperator.rbac.namespaced }}
  {{- with .Values.prometheus.additionalRulesForRole }}
  {{- toYaml . | nindent 0 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-prometheus
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-prometheus
    {{- include "kube-prometheus-stack.labels" . | nindent 4 }}
rules:
{{- end }}
{{- with .Values.prometheus.additionalRulesForClusterRole }}
{{- toYaml . | nindent 0 }}
{{- end }}
{{- end }}
