apiVersion: v2
name: prometheus-node-exporter
appVersion: 1.3.1
version: 3.0.0
type: application
home: https://github.com/prometheus/node_exporter/
sources:
- https://github.com/prometheus/node_exporter/
description: A Helm chart for prometheus node-exporter
keywords:
- node-exporter
- prometheus
- exporter
maintainers:
- email: gianrubio@gmail.com
  name: gianrubio
- name: bismarck
