apiVersion: v2
appVersion: 1.2.2
description: A Helm chart for prometheus node-exporter
name: prometheus-node-exporter
<<<<<<< HEAD
version: 2.2.0
type: application
=======
version: 2.0.0
>>>>>>> bf23c214 (Update: refactoring labels like Helm create command)
home: https://github.com/prometheus/node_exporter/
sources:
- https://github.com/prometheus/node_exporter/
keywords:
- node-exporter
- prometheus
- exporter
maintainers:
- email: gianrubio@gmail.com
  name: gianrubio
- name: vsliouniaev
- name: bismarck
