apiVersion: v2
name: prometheus-node-exporter
description: A Helm chart for prometheus node-exporter
keywords:
  - node-exporter
  - prometheus
  - exporter
type: application
<<<<<<< HEAD
version: 3.4.0
=======
version: 3.4.1
>>>>>>> f8104cfd (bump chart version for prometheus-node-exporter)
appVersion: 1.3.1
home: https://github.com/prometheus/node_exporter/
sources:
  - https://github.com/prometheus/node_exporter/
maintainers:
  - email: gianrubio@gmail.com
    name: gianrubio
  - email: zanhsieh@gmail.com
    name: zanhsieh
