{{- if and .Values.prometheus.enabled .Values.prometheus.prometheusSpec.additionalAlertManagerConfigs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kube-prometheus.fullname" . }}-prometheus-am-confg
  namespace: {{ template "kube-prometheus.namespace" . }}
{{- if .Values.prometheus.prometheusSpec.additionalPrometheusSecretsAnnotations }}
  annotations:
{{ toYaml .Values.prometheus.prometheusSpec.additionalPrometheusSecretsAnnotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "kube-prometheus.name" . }}-prometheus-am-confg
{{ include "kube-prometheus.labels" . | indent 4 }}
data:
  additional-alertmanager-configs.yaml: {{ toYaml .Values.prometheus.prometheusSpec.additionalAlertManagerConfigs | b64enc | quote }}
{{- end }}
