{{- if and .Values.prometheus.enabled .Values.prometheus.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kube-prometheus.prometheus.serviceAccountName" . }}
  namespace: {{ template "kube-prometheus.namespace" . }}
  labels:
    app: {{ template "kube-prometheus.name" . }}-prometheus
{{ include "kube-prometheus.labels" . | indent 4 }}
{{- if .Values.prometheus.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.prometheus.serviceAccount.annotations | indent 4 }}
{{- end }}
imagePullSecrets:
{{ toYaml .Values.global.imagePullSecrets | indent 2 }}
{{- end }}
