{{- if .Values.webConfiguration }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-pushgateway.fullname" . }}
data:
  web-config.yaml: {{ include "prometheus-pushgateway.webConfiguration" . | b64enc}}
{{- end }}
