---
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {{ toYaml .Values.additionalAnnotations | nindent 4 }}
  labels:
    {{- include "prometheus-nginx-exporter.labels" . | indent 4 }}
  name: {{ template "prometheus-nginx-exporter.serviceAccountName" . }}
  namespace: {{ template "prometheus-nginx-exporter.namespace" . }}
{{- end -}}
