apiVersion: v2
name: prometheus-modbus-exporter
description: A Helm chart for prometheus-modbus-exporter

keywords:
  - modbus
  - modbus_exporter
  - metric
  - monitoring
  - prometheus

type: application

# This is the chart version.
version: 0.1.0

# This is the version number of the application being deployed.
# It is recommended to use it with quotes.
appVersion: "0.4.0"

maintainers:
  - name: openenergyprojects
    email: openenergyprojects@gmail.com
