{{- if .Values.checkDeprecation }}
   # The *NilUsesHelmValues can be removed 09/25, about a year after deprecation
   {{- if .Values.prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues }}
      {{ fail "`podMonitorSelectorNilUsesHelmValues` does no longer exist. See README section 'Upgrading Chart'" }}
   {{- end }}
   {{- if .Values.prometheus.prometheusSpec.probeSelectorNilUsesHelmValues }}
      {{ fail "`probeSelectorNilUsesHelmValues` does no longer exist. See README section 'Upgrading Chart'" }}
   {{- end }}
   {{- if .Values.prometheus.prometheusSpec.ruleSelectorNilUsesHelmValues }}
      {{ fail "`ruleSelectorNilUsesHelmValues` does no longer exist. See README section 'Upgrading Chart'" }}
   {{- end }}
   {{- if .Values.prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues }}
      {{ fail "`serviceMonitorSelectorNilUsesHelmValues` does no longer exist. See README section 'Upgrading Chart'" }}
   {{- end }}
   {{- if .Values.prometheus.prometheusSpec.scrapeConfigSelectorNilUsesHelmValues }}
      {{ fail "`scrapeConfigSelectorNilUsesHelmValues` does no longer exist. See README section 'Upgrading Chart'" }}
   {{- end }}
{{- end }}
