{{- if and .Values.kubeProxy.enabled .Values.kubeProxy.serviceMonitor.enabled .Values.kubernetesServiceMonitors.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-kube-proxy
  {{- if .Values.prometheus.prometheusSpec.ignoreNamespaceSelectors }}
  namespace: kube-system
  {{- else }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  {{- end }}
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-kube-proxy
  {{- with .Values.kubeProxy.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  jobLabel: {{ .Values.kubeProxy.serviceMonitor.jobLabel }}
  {{- include "servicemonitor.scrapeLimits" .Values.kubeProxy.serviceMonitor | nindent 2 }}
  selector:
    {{- if .Values.kubeProxy.serviceMonitor.selector }}
    {{ tpl (toYaml .Values.kubeProxy.serviceMonitor.selector | nindent 4) . }}
    {{- else }}
    matchLabels:
      app: {{ template "kube-prometheus-stack.name" . }}-kube-proxy
      release: {{ $.Release.Name | quote }}
    {{- end }}
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  {{- include "kube-prometheus-stack.kubeProxy.endpoint" (list $ "") }}
  {{- if .Values.kubeProxy.serviceMonitor.slis.enabled }}
  {{- include "kube-prometheus-stack.kubeProxy.endpoint" (list $ "slis") }}
    path: /metrics/slis
  {{- end }}
{{- end }}
