---
apiVersion: v2
description: A Helm chart for the Prometheus NGINX Exporter
name: prometheus-nginx-exporter
version: 0.1.0
appVersion: 0.11.0
home: https://github.com/nginxinc/nginx-prometheus-exporter
sources:
- https://github.com/nginxinc/nginx-prometheus-exporter
- https://github.com/prometheus-community/helm-charts
keywords:
- prometheus
- nginx
- monitoring
