{{- if .Values.podSecurityPolicies.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ include "prometheus-logstash-exporter.fullname" . }}
  labels:
    {{- include "prometheus-logstash-exporter.labels" . | nindent 4 }}
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ include "prometheus-logstash-exporter.fullname" . }}
{{- end }}
