kind: Service
apiVersion: v1
metadata:
  name: {{ include "prometheus-logstash-exporter.fullname" . }}
  labels:
    {{- include "prometheus-logstash-exporter.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.metricsPort.name }}
      port: {{ .Values.service.httpPort }}
      protocol: TCP
  selector:
    {{- include "prometheus-logstash-exporter.selectorLabels" . | nindent 4 }}
