name: Check CODEOWNERS

on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: generate CODEOWNERS
        uses: mikefarah/yq@3.4.1
        run: |
          ./scripts/check-codeowners.sh > .github/CODEOWNERS
      - name: check CODEOWNERS for modifications
        run: |
          git diff --exit-code
